# Generated by Django 6.0.6 on 2026-09-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnaliseML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('comprimento_sepala', models.FloatField()),
                ('largura_sepala', models.FloatField()),
                ('comprimento_petala', models.FloatField()),
                ('largura_petala', models.FloatField()),
                ('resultado_decision_tree', models.CharField(blank=True, max_length=100)),
                ('classe_decision_tree', models.IntegerField(blank=True, null=True)),
                ('probabilidades_decision_tree', models.JSONField(blank=True, default=dict)),
                ('resultado_qwen', models.TextField(blank=True)),
                ('qwen_modelo', models.CharField(blank=True, max_length=100)),
                ('qwen_prompt', models.TextField(blank=True)),
                ('qwen_status', models.CharField(default='ok', max_length=30)),
                ('qwen_tempo_ms', models.FloatField(blank=True, null=True)),
                ('metadados', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
